config/routes.rb
Rails.application.routes.draw do
  get '/hall_of_fame', to: 'fame#index', as: 'fame_path'
  devise_for :users

  root "home#welcome"
  resources :genres, only: :index do
    member do
      get "movies"
    end
  end
  resources :movies, only: [:index, :show] do
    resources :comments
    member do
      get :send_info
    end
    collection do
      get :export
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

app/models/genre.rb
# == Schema Information
#
# Table name: genres
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime
#  updated_at :datetime
#

class Genre < ApplicationRecord
  has_many :movies
end

app/models/movie.rb
# == Schema Information
#
# Table name: movies
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  released_at :datetime
#  avatar      :string
#  genre_id    :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Movie < ApplicationRecord
  has_many :comments
  belongs_to :genre
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  validates :phone_number, format: { with: /\A[+]?\d+(?>[- .]\d+)*\z/, allow_nil: true }

  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:name, :email, :password, :password_confirmation]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :check_commented_access, only: [:create]

  def create
    @movie = Movie.find(params[:movie_id])
    @comment = @movie.comments.build(comment_params())
    @comment.user_id = current_user.id
    if @comment.save
      flash[:notice] = "Comment added."
      redirect_to movie_path(@movie)
    else
      flash[:alert] = "There is some errors."
      redirect_to movie_path(@movie)
    end
  end

  def destroy
    @movie = Movie.find(params[:movie_id])
    @comment = @movie.comments.find(params[:id])
    if @comment.user.id == current_user.id
      @comment.destroy
      flash[:notice] = "Comment deleted."
      redirect_to movie_path(@movie)
    else
      flash[:alert] = "That comment does not belongs to you."
      redirect_to movie_path(@movie)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def check_commented_access
    @movie = Movie.find(params[:movie_id])
    !Comment.where(movie_id: @movie.id, user_id: current_user.id).any?
  end
end

app/controllers/fame_controller.rb
class FameController < ApplicationController
  def index
    @users = User.includes(:comments).where("DATE(comments.created_at) > ?", Date.today - 7).references(:comments).limit(10)
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all.decorate
  end

  def movies
    @genre = Genre.find(params[:id]).decorate
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome; end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!, only: [:send_info]

  def index
    @movies = Movie.all.decorate
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def send_info
    @movie = Movie.find(params[:id])
    MovieInfoMailer.send_info(current_user, @movie).deliver_now
    redirect_back(fallback_location: root_path, notice: "Email sent with movie info")
  end

  def export
    file_path = "tmp/movies.csv"
    MovieExporter.new.call(current_user, file_path)
    redirect_to root_path, notice: "Movies exported"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper

  def check_user_commented_movie(user_id, movie_id)
    Comment.where(movie_id: movie_id, user_id: user_id).length >= 1
  end
end

app/helpers/fame_helper.rb
module FameHelper
end

app/views/fame/index.html.haml
.row
  .col-md-8.col-md-offset-2.col-lg-8.col-lg-offset-2
    %h1.text-center Hall of fame
    %table.table.table-striped
      %thead
        %tr
          %th #
          %th Name
          %th Number of comments
      %tbody
        - @users.sort_by { |user| [-user.comments.count] }.each_with_index do |user, i|
          %tr
            %td= i + 1
            %td= user.name
            %td= user.comments.count

app/views/genres/index.html.haml
.row
  .col-md-8.col-md-offset-2.col-lg-8.col-lg-offset-2
    %h1.text-center All genres
    %table.table.table-striped
      %thead
        %tr
          %th #
          %th Name
          %th Number of movies
          %th Created at
      %tbody
        - @genres.each_with_index do |genre, i|
          %tr
            %td= i + 1
            %td= genre.name
            %td= genre.number_of_movies
            %td= genre.created_at

app/views/genres/movies.html.haml
.row
  .col-md-8.col-md-offset-2.col-lg-8.col-lg-offset-2
    %h1.text-center
      Movies by genre:
      = @genre.name
    = render 'movies/movies_table', movies: @genre.movies

app/views/home/welcome.html.haml
.row
  .col-md-8.col-md-offset-2.col-lg-8.col-lg-offset-2
    %h1.text-center Welcome to Pairguru App!
    %p.lead.text-center Place where we examine our candidates

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default.navbar-static-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Pairguru App', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'
      %ul.nav.navbar-nav.navbar-right
        = render 'layouts/navigation_links_right'

app/views/layouts/_navigation_links.html.haml
%li= link_to 'Movies', movies_path
%li= link_to 'Genres', genres_path
%li= link_to 'Hall of Fame', fame_path_url
- if user_signed_in?
  %li= link_to 'Export', export_movies_path

app/views/layouts/_navigation_links_right.html.haml
- if user_signed_in?
  %li= link_to 'Logout', destroy_user_session_path, method: :delete
- else
  %li= link_to 'Login', new_user_session_path
  %li= link_to 'Register', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
    %title= content_for?(:title) ? yield(:title) : 'Pairguru'
    %meta{ name: "description", content: "#{content_for?(:description) ? yield(:description) : 'Props'}" }
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    #announcements-region
    %header
      #header-region
        = render 'layouts/navigation'
    %main
      .container
        #main-region
        = render 'layouts/messages'
        = yield
    %footer.text-center
      Magic by
      = link_to 'netguru', 'https://netguru.co'

app/views/movies/_movies_table.html.haml
%table.table.table-striped
  %tbody
    - movies.each_with_index do |movie, i|
      %tr
        %td= i + 1
        %td
          %img.img-rounded{ src: movie.cover }
        %td
          %h4
            = link_to movie.title, movie_path(movie)
          %p
            %strong
              = link_to movie.genre.name, movies_genre_path(movie.genre)
            = ' (' + movie.released_at.to_s + ')'
          %p= movie.description

app/views/movies/index.html.haml
.row
  .col-md-8.col-md-offset-2.col-lg-8.col-lg-offset-2
    %h1.text-center Movies
    = render 'movies_table', movies: @movies

app/views/movies/show.html.haml
%h1= @movie.title
.jumbotron
  = @movie.description
- if user_signed_in?
  %p= link_to 'Email me details about this movie', send_info_movie_path(@movie), class: 'btn btn-sm btn-default'

  %br/
%h2
  Comments below
#comments
  - @movie.comments.each do |comment|
    = comment.user.email
    %br/
    = comment.content
    %br/
    = time_ago_in_words(comment.created_at)
    %br/
    - if current_user != nil
      - if comment.user.id == current_user.id
        %p
          = link_to 'Delete', [comment.movie, comment], method: :delete, data: { confirm: "Are you sure?"}
    %br/
- if current_user != nil
  - if !check_user_commented_movie(current_user.id, @movie.id)
    %h3 Add a comment:
    = simple_form_for([@movie, @movie.comments.build]) do |form|
      = form.input  :content
      = form.button :submit, html: {class: 'btn btn-sm btn-default'}